<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>ログイン成功</title>
	<link rel="stylesheet" href="/css/main.css">
</head>
<body>
<div id="out">

	<div id="head">
		<h1>ログイン成功</h1>
		<h2>あなたもログインできてしまいましたね？</h2>
	</div>

	<div id="main">
		<!--div id="menu">
			<a href="/index.html">メニュー１</a> |
			<a href="/index.html">メニュー２</a> |
			<a href="/index.html">メニュー３</a> |
			<a href="/index.html">メニュー４</a>
		</div-->

		<h3>ログインに成功してしまいました</h3>
		<p>ユーザーID :</p>
		<p class="mgl-2em"><?=$this->userId?></p>
		<p>パスワード :</p>
		<p class="mgl-2em">*****</p>

		<h4>ご利用規約</h4>
		<ul>
			<li>ざんねんながら、これはテストサイトです。</li>
		</ul>
	</div>

	<div id="footer">
		Copyright &copy; <a href="/">はじめてのZendFramework</a> All Rights Reserved.
	</div>
</div>
</body>
</html>